import '../models/exercise.dart';
import '../utils/constants.dart';

/// Rutina por defecto que se inserta la primera vez que se abre la app.
class DefaultRoutine {
  static List<Exercise> all() {
    return [
      // ───────────────────── LUNES — Push + Cardio ─────────────────────
      Exercise(
        dayOfWeek: Weekday.monday,
        name: 'Press inclinado con mancuernas',
        sets: 2,
        repsMin: 6,
        repsMax: 8,
        orderIndex: 0,
      ),
      Exercise(
        dayOfWeek: Weekday.monday,
        name: 'Hombro elevación unilateral con polea',
        sets: 3,
        repsMin: 6,
        repsMax: 8,
        orderIndex: 1,
      ),
      Exercise(
        dayOfWeek: Weekday.monday,
        name: 'Pec deck en polea',
        sets: 3,
        repsMin: 6,
        repsMax: 8,
        orderIndex: 2,
      ),
      Exercise(
        dayOfWeek: Weekday.monday,
        name: 'Hombro tirones a la cara con polea',
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        orderIndex: 3,
      ),
      Exercise(
        dayOfWeek: Weekday.monday,
        name: 'Fondos con peso del cuerpo',
        sets: 3,
        repsMin: 6,
        repsMax: 8,
        orderIndex: 4,
        notes: 'Si estás cómodo, agrega lastre.',
      ),
      Exercise(
        dayOfWeek: Weekday.monday,
        name: 'Overhead extensions',
        sets: 3,
        repsMin: 5,
        repsMax: 10,
        orderIndex: 5,
      ),
      Exercise(
        dayOfWeek: Weekday.monday,
        name: 'Extensión de tríceps barra',
        sets: 2,
        repsMin: 6,
        repsMax: 8,
        orderIndex: 6,
      ),
      Exercise(
        dayOfWeek: Weekday.monday,
        name: 'Cardio caminata moderada',
        sets: 1,
        durationSecondsMin: 15 * 60,
        durationSecondsMax: 20 * 60,
        trackingType: TrackingType.duration,
        orderIndex: 7,
      ),

      // ───────────────────── MARTES — Legs + Abs ─────────────────────
      Exercise(
        dayOfWeek: Weekday.tuesday,
        name: 'Extensiones',
        sets: 2,
        repsMin: 8,
        repsMax: 12,
        orderIndex: 0,
      ),
      Exercise(
        dayOfWeek: Weekday.tuesday,
        name: 'Peso muerto rumano con barra',
        sets: 2,
        repsMin: 8,
        repsMax: 12,
        orderIndex: 1,
      ),
      Exercise(
        dayOfWeek: Weekday.tuesday,
        name: 'Hip thrust',
        sets: 2,
        repsMin: 8,
        repsMax: 12,
        orderIndex: 2,
      ),
      Exercise(
        dayOfWeek: Weekday.tuesday,
        name: 'Prensa',
        sets: 2,
        repsMin: 8,
        repsMax: 12,
        orderIndex: 3,
      ),
      Exercise(
        dayOfWeek: Weekday.tuesday,
        name: 'Pantorrilla',
        sets: 4,
        repsMin: 15,
        repsMax: 20,
        orderIndex: 4,
      ),
      Exercise(
        dayOfWeek: Weekday.tuesday,
        name: 'Abdominales en polea alta',
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        orderIndex: 5,
      ),
      Exercise(
        dayOfWeek: Weekday.tuesday,
        name: 'Planchas',
        sets: 3,
        durationSecondsMin: 30,
        durationSecondsMax: 60,
        trackingType: TrackingType.duration,
        orderIndex: 6,
      ),

      // ───────────────────── MIÉRCOLES — Descanso ─────────────────────
      // (sin ejercicios; el usuario puede agregar lo que quiera)

      // ───────────────────── JUEVES — Pull + Cardio ─────────────────────
      Exercise(
        dayOfWeek: Weekday.thursday,
        name: 'Lat pulldown',
        sets: 2,
        repsMin: 6,
        repsMax: 8,
        orderIndex: 0,
      ),
      Exercise(
        dayOfWeek: Weekday.thursday,
        name: 'Remo en máquina',
        sets: 2,
        repsMin: 6,
        repsMax: 8,
        orderIndex: 1,
      ),
      Exercise(
        dayOfWeek: Weekday.thursday,
        name: 'Pull over dorsales',
        sets: 2,
        repsMin: 8,
        repsMax: 10,
        orderIndex: 2,
      ),
      Exercise(
        dayOfWeek: Weekday.thursday,
        name: 'Trapecio',
        sets: 4,
        repsMin: 10,
        repsMax: 15,
        orderIndex: 3,
      ),
      Exercise(
        dayOfWeek: Weekday.thursday,
        name: 'Predicador',
        sets: 2,
        repsMin: 6,
        repsMax: 8,
        orderIndex: 4,
      ),
      Exercise(
        dayOfWeek: Weekday.thursday,
        name: 'Curl de bíceps sentado',
        sets: 2,
        repsMin: 6,
        repsMax: 8,
        orderIndex: 5,
      ),
      Exercise(
        dayOfWeek: Weekday.thursday,
        name: 'Cardio caminata moderada',
        sets: 1,
        durationSecondsMin: 15 * 60,
        durationSecondsMax: 20 * 60,
        trackingType: TrackingType.duration,
        orderIndex: 6,
      ),

      // ───────────────────── VIERNES — Legs + Abs ─────────────────────
      Exercise(
        dayOfWeek: Weekday.friday,
        name: 'Extensiones',
        sets: 2,
        repsMin: 8,
        repsMax: 12,
        orderIndex: 0,
      ),
      Exercise(
        dayOfWeek: Weekday.friday,
        name: 'Sentadilla Smith',
        sets: 2,
        repsMin: 8,
        repsMax: 12,
        orderIndex: 1,
      ),
      Exercise(
        dayOfWeek: Weekday.friday,
        name: 'Curl de piernas acostado',
        sets: 2,
        repsMin: 8,
        repsMax: 12,
        orderIndex: 2,
      ),
      Exercise(
        dayOfWeek: Weekday.friday,
        name: 'Aductores',
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        orderIndex: 3,
      ),
      Exercise(
        dayOfWeek: Weekday.friday,
        name: 'Abductores',
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        orderIndex: 4,
      ),
      Exercise(
        dayOfWeek: Weekday.friday,
        name: 'Abdominales rotación de torso con polea',
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        orderIndex: 5,
      ),
      Exercise(
        dayOfWeek: Weekday.friday,
        name: 'Planchas',
        sets: 3,
        durationSecondsMin: 30,
        durationSecondsMax: 60,
        trackingType: TrackingType.duration,
        orderIndex: 6,
      ),

      // ───────────────────── SÁBADO — Trote opcional ─────────────────────
      Exercise(
        dayOfWeek: Weekday.saturday,
        name: 'Trote',
        sets: 1,
        durationSecondsMin: 20 * 60,
        durationSecondsMax: 30 * 60,
        trackingType: TrackingType.duration,
        orderIndex: 0,
        notes: 'Opcional, si es posible.',
      ),
    ];
  }
}